### ISSUE TITLE
Script lags heavily after a few minutes of running

### ISSUE THREAD

**Issue by Jocomol** [LukeZzzHD/EnergyAirBot2019#2]
Probably a issue with a full RAM.

**Comment by LukeZzzHD** [comment]
That is because the script is currently writing every question and the right answer to the console. I am working on a popup, in which you can turn off the logging.

**Comment by LukeZzzHD** [comment]
I am going to close this issue. I made the logging optional, so it doesn't fill the RAM if you leave the bot running for some time.

Please read the release notes from release v1.3 [here](https://github.com/LukeZzzHD/EnergyAirBot2019/releases/tag/v1.3)
