### ISSUE TITLE
Lose

### ISSUE THREAD

**Issue by AVREOS** [LukeZzzHD/EnergyAirBot2019#3]
Die 'Leider verloren' Seite wird nicht übersprungen.

**Comment by LukeZzzHD** [comment]
Welches Release verwendest du?

**Comment by AVREOS** [comment]
Release 4 (v1.3)

**Comment by AVREOS** [comment]
Ich weis nicht ob es was mit dem zu tun hat aber  ich bekomme in der Console diese Fehlermeldung 
Uncaught TypeError: Cannot read property 'classList' of null
    at a.checkIfAdEmpty (app.js?id=cdf0586d2d0a9b9b4824:1)
    at a.n [as checkIfAdEmpty] (app.js?id=cdf0586d2d0a9b9b4824:1)
    at app.js?id=cdf0586d2d0a9b9b4824:1

**Comment by LukeZzzHD** [comment]
Ich erhalte diese Fehlermeldung nicht, aber das seiht stark nach Werbung aus welche nicht geladen werden konnte. Das ist nicht der BOT, sondern die Seite selber. Ich schaue es an und werde es bis Morgen lösen.

**Comment by AVREOS** [comment]
Gut
Danke dir vielmals

**Comment by LukeZzzHD** [comment]
Ich habe ein neues Release veröffentlicht: [Release v1.4](https://github.com/LukeZzzHD/EnergyAirBot2019/releases/tag/v1.4)

Damit sollte der Bug "eigentlich" nicht mehr auftreten. Falls doch, bitte das Issue wieder eröffnen.
